### ISSUE TITLE
Matching problems with `[0-9][0-9]`

### ISSUE THREAD

**Issue by q3cpma** [telekons/one-more-re-nightmare#18] opened 2022-05-08 12:44 UTC
```
CL-USER> (one-more-re-nightmare:all-matches "[0-1][0-9][0-9]" "192")
NIL
CL-USER> (one-more-re-nightmare:all-matches "[0-9][0-9]" "192")
NIL
CL-USER> (one-more-re-nightmare:all-matches "[0-9][0-9]" "1921")
(#(2 4))
```

Using latest Quicklisp (20220331) with SBCL 2.2.4.

**Comment by no-defun-allowed** [comment] 2022-05-09 00:12
The issue is that the Quicklisp release of OMRN confuses half-open and open sets. The parser constructs a set thinking that `(symbol-range A B)` constructs a set including A and B, whereas it constructs a set including A but not B. This is fixed in newer OMRN, but I am waiting for the next Quicklisp release.

For the meanwhile, this can be fixed by replacing lines 102-106 of Code/Interface/syntax.lisp with

```lisp
(esrap:defrule character-range-range
    (and character "-" character)
  (:destructure (low dash high)
    (declare (ignore dash))
    (symbol-range (char-code low) (1+ (char-code high)))))
```

which will produce the correct set.

**Closed as completed by no-defun-allowed** 2022-05-09 00:12 UTC
